# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger on fpga changes in titanium-master
# execute a build for each commit
trigger:
  batch: false
  branches:
    include:
    - titanium-master
    - titanium-revb
  paths:
    include:
    - fpga/nitools/x400/*
    - fpga/usrp3/lib/*
    - fpga/usrp3/tools/*
    - fpga/usrp3/top/x400/*

# opt out of any PR checking
pr: none

jobs:
# -------------------------------------------------------------------
# Build XG FPGA (100 MHz)
# -------------------------------------------------------------------
- template: templates/fpga_build.yml
  parameters:
    target: X410_XG_100
    timeout: 360

# -------------------------------------------------------------------
# Build X4 FPGA (200 MHz)
# -------------------------------------------------------------------
- template: templates/fpga_build.yml
  parameters:
    target: X410_X4_200
    timeout: 360

# -------------------------------------------------------------------
# Build C1 FPGA (400 MHz)
# -------------------------------------------------------------------
#- template: templates/fpga_build.yml
#  parameters:
#    target: X410_C1_400
#    timeout: 360

# -------------------------------------------------------------------
# Make CPLD
# -------------------------------------------------------------------
- template: templates/mb_cpld_build.yml

# -------------------------------------------------------------------
# Make ZR CPLD
# -------------------------------------------------------------------
- template: templates/zr_cpld_build.yml

# -------------------------------------------------------------------
# Build Regmap
# -------------------------------------------------------------------
- template: templates/regmap.yml
